### ISSUE TITLE
Assertion `!posix::pthread_mutex_destroy(&m)' failed.

### ISSUE THREAD

**Issue by dudektria** [tbereau/auto_martini#1]
When I run `$ ./auto_martini --smi "N1=C(N)NN=C1N" --mol GUA` (taken from the documentation), I receive the following on Ubuntu 15.04 64bits:

    ;;;; GENERATED WITH auto-martini
    ; INPUT SMILES: N1=C(N)NN=C1N
    ; Tristan Bereau (2014)

    [moleculetype]
    ; molname       nrexcl
      GUA           2

    [atoms]
    ; id    type    resnr   residu  atom    cgnr    charge  smiles
      1     SP2     1       GUA     S01     1       0     ; Nc1ncnn1
      2     SP2     1       GUA     S02     2       0     ; Nc1ncnn1

    [constraints]
    ;  i   j     funct   length
       1   2     1       0.21

    python: /usr/include/boost/thread/pthread/mutex.hpp:108: boost::mutex::~mutex(): Assertion `!posix::pthread_mutex_destroy(&m)' failed.
    [1]    31433 abort (core dumped)  ./auto_martini --smi "N1=C(N)NN=C1N" --mol GUA

What am I doing wrong?

Best regards,
Felipe Schneider

**Comment by tbereau** [comment]
Hi Felipe,

I haven't been able to reproduce this error on any of my machines, but apparently the boost library is not able to properly close the multiple processes (pthreads) on your machine when the code finishes. I'm not sure why that is, but may have to do with strange interactions between RDKit and Boost. In any event, that happens only when the program closes, so any of the results you get aren't affected. I'll keep you posted if I find out more.

Best,
Tristan

**Comment by glosar** [comment]
Hi Tristan,
I would like to use auto_martini so I installed it with all the dependencies required.
When I try to run it, on benzene or n-butane for example, I receive the following error:

$ ./auto_martini --smi "CCCC" --mol NBUT
Traceback (most recent call last):
  File "./auto_martini", line 1203, in <module>
    ringAtomsFlat, True)

Any help is welcome,
best regards

Gloria

**Comment by tbereau** [comment]
Hi Gloria,

I can't reproduce your error message. Which python version are you using? Maybe you could try with a different python version, or even within ipython (if you have it). In the ipython's command line:
````
%run auto_martini --smi "CCCC" --mol NBUT
````
Does that provide a more detailed error message?

Best,
Tristan

**Comment by glosar** [comment]
Dear Tristan,
thank you for your reply.

I have recently installed the CentOS7 on my 
workstation and the python version as read from 
print(sys.version) is:

2.7.5 (default, Jun 24 2015, 
00:41:19)                                                                         
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] 

yum info also gives the following details:

Name        : python
Arch        : x86_64
Version     : 2.7.5
Release     : 18.el7_1.1

May be that I need of another version?

Regards,
Gloria


-- 
Gloria Anna Ada Saracino PhD

Center of Nanomedicine and Tissue Engineering 
(CNTE)
A.O. Ospedale Niguarda Ca' Granda
Piazza dell'Ospedale Maggiore 3
Milan, 20162, Italy

tel. +39 02 64447527
fax. +39 02 87073821

Università degli Studi di Milano-Bicocca
Dipartimento di Biotecnologie e Bioscienze
Piazza della Scienza 2
Milan, 20126, Italy

tel. +39 02 6448 3312
fax. +39 02 6448 3314
On Wed, 16 Sep 2015 23:12:59 -0700
 Tristan Bereau <notifications@github.com> 
wrote:

**Comment by tbereau** [comment]
Dear Gloria,

Python 2.7.5 is just fine. What's puzzling me is the lack of information in
the error message, there's usually a bit more about what's causing
problems.

Do you happen to have ipython, or any other version of python, installed as
well? Does it give you the same error message?

You can also try an alternative branch, see if you get the same error:
````
git checkout refactor
python auto_martini.py --smi "CCCC" --mol NBUT
````
Let me know what happens.

Best,
Tristan

**Comment by glosar** [comment]
Typing python followed by tab key I find:
python            python2           
python2.7         python2.7-config  
python2-config    python-config

All of them are located in /usr/bin and running 
diff command any difference appears.
Also sys.version gives the same result.
yum install info answers only about python 
giving the details reported in the previous 
email.

Can I do something else?

Thanks,

Gloria

-- 
Gloria Anna Ada Saracino PhD

Center of Nanomedicine and Tissue Engineering 
(CNTE)
A.O. Ospedale Niguarda Ca' Granda
Piazza dell'Ospedale Maggiore 3
Milan, 20162, Italy

tel. +39 02 64447527
fax. +39 02 87073821

Università degli Studi di Milano-Bicocca
Dipartimento di Biotecnologie e Bioscienze
Piazza della Scienza 2
Milan, 20126, Italy

tel. +39 02 6448 3312
fax. +39 02 6448 3314
On Thu, 17 Sep 2015 00:31:16 -0700
 Tristan Bereau <notifications@github.com> 
wrote:
> Dear Gloria,
> 
> Python 2.7.5 is just fine. What's puzzling me 
>is the lack of information in
> the error message, there's usually a bit more 
>about what's causing
> problems.
> 
> Do you happen to have ipython, or any other 
>version of python, installed as
> well? Does it give you the same error message?
> 
> You can also try an alternative branch, see if 
>you get the same error:
> ````
> git checkout refactor
> python auto_martini.py --smi "CCCC" --mol NBUT
> ````
> Let me know what happens.
> 
> Best,
> Tristan
> 
> 
> 
> On Thu, Sep 17, 2015 at 9:05 AM, glosar

**Comment by tbereau** [comment]
Dear Gloria,

Without an explicit error message it's difficult to guess what's going on.
Maybe you could try installing a different version of python (e.g., 3.0)
and see whether the same error comes back, and if so, whether you get a
more explicit error message.

Best,
Tristan

**Comment by glosar** [comment]
Dear Tristan,
I resolved using python3 on auto_martini.py

Thank you for your help!

I have another question: I've seen in the code 
that the heavy atoms limit is 25, so I tried to 
submit the SMCC (24 heavy atoms) molecule 
(smile:
C1CC(CCC1CN2C(=O)C=CC2=O)C(=O)ON3C(=O)CCC3=O). 
Unfortunately even if the process starts and 
runs without giving any error, in few minutes it 
falls in D state any output is produced.
Have you some hint about it?

Regards,
Gloria

-- 
Gloria Anna Ada Saracino PhD

Center of Nanomedicine and Tissue Engineering 
(CNTE)
A.O. Ospedale Niguarda Ca' Granda
Piazza dell'Ospedale Maggiore 3
Milan, 20162, Italy

tel. +39 02 64447527
fax. +39 02 87073821

Università degli Studi di Milano-Bicocca
Dipartimento di Biotecnologie e Bioscienze
Piazza della Scienza 2
Milan, 20126, Italy

tel. +39 02 6448 3312
fax. +39 02 6448 3314
On Thu, 17 Sep 2015 04:26:57 -0700
 Tristan Bereau <notifications@github.com> 
wrote:
> Dear Gloria,
> 
> Without an explicit error message it's 
>difficult to guess what's going on.
> Maybe you could try installing a different 
>version of python (e.g., 3.0)
> and see whether the same error comes back, and 
>if so, whether you get a
> more explicit error message.
> 
> Best,
> Tristan
> 
> On Thu, Sep 17, 2015 at 9:53 AM, glosar

**Comment by tbereau** [comment]
Dear Gloria,

Very glad Python 3 resolved the first issue.

It may be that the error you get is due to memory limitations on your machine. I've ran the code on that Smiles string. Here's the output:

mol.itp
=====
; GENERATED WITH auto_martini.py
; None
; Tristan Bereau (2014)

[moleculetype]
; molname       nrexcl
  MOL           2

[atoms]
; id    type    resnr   residue  atom    cgnr    charge  smiles
    1     SC2     1     MOL       S01     1         0   ; [C]1[C][C][C][C][C]1
    2     SC2     1     MOL       S02     2         0   ; [C]1[C][C][C][C][C]1
    3     SC1     1     MOL       S03     3         0   ; [C][C]1[C][C][C][C][C]1
    4     SP2     1     MOL       S04     4         0   ; O=C1[C]=[C][C][N]1
    5     SP2     1     MOL       S05     5         0   ; O=C1[C]=[C][C][N]1
    6     P2      1     MOL       P01     6         0   ; [N]O[C]=O
    7     SP2     1     MOL       S06     7         0   ; O=C1[C][C][C][N]1
    8     SP2     1     MOL       S07     8         0   ; O=C1[C][C][C][N]1

[bonds]
; i j     funct     length    force.c.
  1 6       1         0.31     1250
  3 5       1         0.36     1250
  6 8       1         0.25     1250

[constraints]
;  i   j     funct   length
   1   2     1       0.26
   1   3     1       0.26
   2   3     1       0.26
   4   5     1       0.22
   7   8     1       0.23

[angles]
; i j k         funct   angle   force.c.
  1 3 5         2       98.6    25.0
  1 6 8         2       147.2   45.0
  2 1 6         2       65.2    25.0
  2 3 5         2       158.3   25.0
  3 1 6         2       101.3   25.0
  3 5 4         2       62.5    45.0
  6 8 7         2       63.8    45.0

[dihedrals]
;  i     j    k    l   funct   angle  force.c.
   1     2    3    4       2     -142.7   10.0
   1     3    2    6       2     -52.1   10.0
   1     6    2    3       2     48.7    10.0
   2     1    3    4       2     167.2   10.0
   2     3    1    6       2     52.1    10.0
   2     6    1    3       2     -48.4   10.0
   3     1    2    6       2     121.6   10.0
   3     2    1    6       2     -121.6   10.0



atomistic.gro
==========

MOL generated from auto_martini.py
   24
    1MOL    C      1   0.054  -0.127  -0.189
    2MOL    C      2  -0.089  -0.082  -0.155
    3MOL    C      3  -0.163  -0.189  -0.073
    4MOL    C      4  -0.070  -0.269   0.022
    5MOL    C      5   0.054  -0.187   0.062
    6MOL    C      6   0.140  -0.149  -0.061
    7MOL    C      7   0.227  -0.026  -0.028
    8MOL    N      8   0.327  -0.003  -0.132
    9MOL    C      9   0.444  -0.079  -0.160
   10MOL    O     10   0.473  -0.187  -0.103
   11MOL    C     11   0.525  -0.012  -0.261
   12MOL    C     12   0.464   0.101  -0.294
   13MOL    C     13   0.342   0.111  -0.216
   14MOL    O     14   0.260   0.206  -0.221
   15MOL    C     15  -0.276  -0.126   0.004
   16MOL    O     16  -0.395  -0.157  -0.023
   17MOL    O     17  -0.248  -0.031   0.103
   18MOL    N     18  -0.342   0.012   0.194
   19MOL    C     19  -0.429  -0.070   0.271
   20MOL    O     20  -0.449  -0.192   0.246
   21MOL    C     21  -0.487   0.001   0.389
   22MOL    C     22  -0.418   0.139   0.387
   23MOL    C     23  -0.331   0.133   0.266
   24MOL    O     24  -0.254   0.226   0.231
  10.00000  10.00000  10.00000


coarse_grained.gro
===============

MOL generated from auto_martini.py
    8
    1MOL    S01    1  -0.089  -0.082  -0.155
    2MOL    S02    2  -0.070  -0.269   0.022
    3MOL    S03    3   0.140  -0.149  -0.061
    4MOL    S04    4   0.444  -0.079  -0.160
    5MOL    S05    5   0.342   0.111  -0.216
    6MOL    P01    6  -0.248  -0.031   0.103
    7MOL    S06    7  -0.429  -0.070   0.271
    8MOL    S07    8  -0.331   0.133   0.266
  10.00000  10.00000  10.00000

**Comment by glosar** [comment]
Dear Tristan,

thank you very much,


Gloria
