### ISSUE TITLE
Vcclabs website down - is it OK to use rdkit.Chem.Crippen module for ALOGP calculation?

### ISSUE THREAD

**Issue by ljmartin** [tbereau/auto_martini#23]
Love this tool so thankyou!

The vcclabs website is down, meaning ALOGP calculation fails in `smi2alogps`. Granted that may be temporary, but is there a reason to prefer vcclabs calculation of logp over rdkit? 

PS if it's still down in future and someone's looking to run auto_martini anyway, just replace smi2alogps with:
```
def smi2alogps(forcepred, smi, wc_log_p, bead, trial=False):
    """Returns water/octanol partitioning free energy
    according to ALOGPS"""
    from rdkit.Chem import Crippen
    from rdkit import Chem

    return convert_log_k( Crippen.MolLogP( Chem.MolFromSmiles(smi) ) )
```

**Comment by tbereau** [comment]
Thanks for the note! From what I remember the logp predictors in rdkit are atom-based, whereas ALOGPS is fragment based, offering higher accuracy. Hopefully the vcclab website comes back up, otherwise we may need a different solution. Your workaround is sound, although it has already been implemented: you can simply use the flag `--fpred` to get a prediction with Wildman-Crippen. Somehow the help options incorrectly lists `--fpred` as producing a verbose output, but it really uses this logp predictor.

**Comment by ljmartin** [comment]
Great - cheers!
