### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by LIVazquezS** [tbereau/auto_martini#51]
Hi all,

Thanks for your nice code. I want to make an observation. While installing automartini in a mamba environment, I noticed the package `charset_normalizer` is required. Then, if you install Automartini with pip and later try to use or install Jupyter in the same environment, it results in an error for double importation. This is most likely because you end up with a version of the mentioned package in pip and a different one in conda. would it be possible to avoid this? 

A second observation is while using conda-lock in macOS. I was unable to complete the environment creation because of a problem with formatting; see this issue (https://github.com/ContinuumIO/anaconda-issues/issues/11028).

The solution for the first problem was to install Jupyter from Pip. But for the second issue, I could not come up with something that did not involve a massive formating of my computer. 

Kind regards,

L

**Comment by anabiman** [comment]
1. In general, it's not a good idea to mix pip and conda. It's always best to stick with either pip/poetry or conda/mamba.
2. I can run: ```conda create -n test-ncurses -c anaconda ncurses -y``` on my Mac without any issues and I never made any changes to my filesystem (it's by default case insensitive). Since this has nothing to do with auto_martini, I suggest you open a new issue on anaconda or follow up with the existing one (11028). Some solns I can think on top of my head would be to use a VM, containers, or switch to Linux altogether because it's just a better OS :-)
